DROP DATABASE IF EXISTS waterfall_db;
CREATE DATABASE waterfall_db;
USE waterfall_db;

CREATE TABLE USUARIO(
  LOGIN VARCHAR(50) NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  SENHA VARCHAR(50) NOT NULL,
  ADMIN INT(1) NOT NULL,
  PRIMARY KEY(LOGIN)
);

CREATE TABLE CATEGORIA(
  NOME_CATEGORIA VARCHAR(50) NOT NULL,
  PRIMARY KEY (NOME_CATEGORIA)
);

CREATE TABLE PRODUTO(
  ID_PRODUTO INT(11) NOT NULL AUTO_INCREMENT,
  NOME_CATEGORIA VARCHAR(50) NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  DESCRICAO VARCHAR(200),
  PRECO DECIMAL(10,2) NOT NULL,
  PRIMARY KEY(ID_PRODUTO),
  FOREIGN KEY (NOME_CATEGORIA) REFERENCES CATEGORIA(NOME_CATEGORIA),
  UNIQUE(NOME)
);

CREATE TABLE PEDIDO(
  ID_PEDIDO INT(11) NOT NULL AUTO_INCREMENT,
  STATUS INT(11) NOT NULL,
  LOGIN_USUARIO VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID_PEDIDO),
  FOREIGN KEY (LOGIN_USUARIO) REFERENCES USUARIO(LOGIN)
);

CREATE TABLE ITEM_PEDIDO(
  ID_PEDIDO INT(11) NOT NULL,
  ID_PRODUTO INT(11) NOT NULL,
  QUANTIDADE INT(11) NOT NULL,
  PRIMARY KEY(ID_PEDIDO, ID_PRODUTO),
  FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

CREATE TABLE PAGAMENTO(
  CODIGO INT(11) NOT NULL AUTO_INCREMENT,
  TIPO INT(11) NOT NULL,
  ENDERECO VARCHAR(200),
  ID_PEDIDO INT(11) NOT NULL,
  PRIMARY KEY(CODIGO),
  FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
);

CREATE TABLE INFORMACAO(
  ID_PRODUTO INT(11) NOT NULL,
  TITULO VARCHAR(50) NOT NULL,
  CORPO VARCHAR(200) NOT NULL,
  PRIMARY KEY(ID_PRODUTO, TITULO),
  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);