INSERT INTO USUARIO(LOGIN, NOME, SENHA, ADMIN) 
VALUES("rochinha@gmail.com", "Rochinha Gamer", "1234", 1);

INSERT INTO USUARIO(LOGIN, NOME, SENHA, ADMIN) 
VALUES("ana@outlook.com", "Ana", "5678", 0);

INSERT INTO USUARIO(LOGIN, NOME, SENHA, ADMIN) 
VALUES("gisele@protonmail.com", "Gisele", "1423", 1);

INSERT INTO USUARIO(LOGIN, NOME, SENHA, ADMIN) 
VALUES("andre@gmail.com", "Andre", "101010", 0);

INSERT INTO USUARIO(LOGIN, NOME, SENHA, ADMIN) 
VALUES("admin", "admin", "admin", 1);

INSERT INTO CATEGORIA VALUES("JOGOS");
INSERT INTO CATEGORIA VALUES("COMPUTADORES DE MESA");
INSERT INTO CATEGORIA VALUES("NOTEBOOKS");
INSERT INTO CATEGORIA VALUES("CELULARES");
INSERT INTO CATEGORIA VALUES("PEÇAS");

INSERT INTO PRODUTO(ID_PRODUTO, NOME_CATEGORIA, NOME, DESCRICAO, PRECO)
VALUES(12011,"CELULARES", "Samsung Galaxy S23 128GB", 
"Smartphone Samsung Galaxy S23 128GB Verde 5G 8GB RAM 6,1 Câm Tripla + Selfie 12MP", 
3869.10);

INSERT INTO PRODUTO(ID_PRODUTO, NOME_CATEGORIA, NOME, DESCRICAO, PRECO)
VALUES(141423,"JOGOS", "FIFA2024", 
"EA Sports FC 24 - PlayStation 5", 
316.70);

INSERT INTO PRODUTO(ID_PRODUTO, NOME_CATEGORIA, NOME, DESCRICAO, PRECO)
VALUES(9897634,"NOTEBOOKS", "Notebook acer Aspire 5 A515", 
"Notebook acer Aspire 5 A515-54G-53GP CI5 8 GB 256 GB SSD NVDIA® GeForce MX250 15.6 Win 10", 
4773.70);

INSERT INTO PRODUTO(ID_PRODUTO, NOME_CATEGORIA, NOME, DESCRICAO, PRECO)
VALUES(98786354,"PEÇAS", "Memória RAM 16GB", 
"Memória de 16GB DIMM DDR4 3200Mhz FURY Beast 1,35V 1Rx8 288 pinos para desktop/gamers, Preto", 
262.97);

INSERT INTO PRODUTO(ID_PRODUTO, NOME_CATEGORIA, NOME, DESCRICAO, PRECO)
VALUES(954,"COMPUTADORES DE MESA", "PC GAMER RYZEN", 
"PC GAMER RYZEN 7 5700G, 16GB DDR4 3200MHZ, SSD M.2 NVME 250GB, VEGA 7", 
2679);

INSERT INTO PRODUTO(ID_PRODUTO, NOME_CATEGORIA, NOME, DESCRICAO, PRECO)
VALUES(35709874,"JOGOS", "Lies of P", 
"Lies of P - PlayStation 4", 
2679);

